/* C file for designated initializers */
#include "wasmdefs.h"

const opaccess opcode_access[] = {
    [WASM_OP_I32_LOAD] = { "i32_load", LOAD, 4, NON_ATOMIC },
    [WASM_OP_I64_LOAD] = { "i64_load", LOAD, 8, NON_ATOMIC },
    [WASM_OP_F32_LOAD] = { "f32_load", LOAD, 4, NON_ATOMIC },
    [WASM_OP_F64_LOAD] = { "f64_load", LOAD, 8, NON_ATOMIC },
    [WASM_OP_I32_LOAD8_S] = { "i32_load8_s", LOAD, 1, NON_ATOMIC },
    [WASM_OP_I32_LOAD8_U] = { "i32_load8_u", LOAD, 1, NON_ATOMIC },
    [WASM_OP_I32_LOAD16_S] = { "i32_load16_s", LOAD, 2, NON_ATOMIC },
    [WASM_OP_I32_LOAD16_U] = { "i32_load16_u", LOAD, 2, NON_ATOMIC },
    [WASM_OP_I64_LOAD8_S] = { "i64_load8_s", LOAD, 1, NON_ATOMIC },
    [WASM_OP_I64_LOAD8_U] = { "i64_load8_u", LOAD, 1, NON_ATOMIC },
    [WASM_OP_I64_LOAD16_S] = { "i64_load16_s", LOAD, 2, NON_ATOMIC },
    [WASM_OP_I64_LOAD16_U] = { "i64_load16_u", LOAD, 2, NON_ATOMIC },
    [WASM_OP_I64_LOAD32_S] = { "i64_load32_s", LOAD, 4, NON_ATOMIC },
    [WASM_OP_I64_LOAD32_U] = { "i64_load32_u", LOAD, 4, NON_ATOMIC },
    [WASM_OP_I32_ATOMIC_LOAD] = { "i32_atomic_load", LOAD, 4, NON_ATOMIC },
    [WASM_OP_I64_ATOMIC_LOAD] = { "i64_atomic_load", LOAD, 8, NON_ATOMIC },
    [WASM_OP_I32_ATOMIC_LOAD8_U] = { "i32_atomic_load8_u", LOAD, 1, NON_ATOMIC },
    [WASM_OP_I32_ATOMIC_LOAD16_U] = { "i32_atomic_load16_u", LOAD, 2, NON_ATOMIC },
    [WASM_OP_I64_ATOMIC_LOAD8_U] = { "i64_atomic_load8_u", LOAD, 1, NON_ATOMIC },
    [WASM_OP_I64_ATOMIC_LOAD16_U] = { "i64_atomic_load16_u", LOAD, 2, NON_ATOMIC },
    [WASM_OP_I64_ATOMIC_LOAD32_U] = { "i64_atomic_load32_u", LOAD, 4, NON_ATOMIC },

    [WASM_OP_I32_STORE] = { "i32_store", STORE, 4, NON_ATOMIC },
    [WASM_OP_I32_STORE8] = { "i32_store8", STORE, 1, NON_ATOMIC },
    [WASM_OP_I32_STORE16] = { "i32_store16", STORE, 2, NON_ATOMIC },
    [WASM_OP_I32_ATOMIC_STORE] = { "i32_atomic_store", STORE, 4 },
    [WASM_OP_I32_ATOMIC_STORE8] = { "i32_atomic_store8", STORE, 1 },
    [WASM_OP_I32_ATOMIC_STORE16] = { "i32_atomic_store16", STORE, 2 },
    [WASM_OP_I32_ATOMIC_RMW_ADD] = { "i32_atomic_rmw_add", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_ADD_U] = { "i32_atomic_rmw8_add_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_ADD_U] = { "i32_atomic_rmw16_add_u", STORE, 2 },
    [WASM_OP_I32_ATOMIC_RMW_SUB] = { "i32_atomic_rmw_sub", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_SUB_U] = { "i32_atomic_rmw8_sub_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_SUB_U] = { "i32_atomic_rmw16_sub_u", STORE, 2 },
    [WASM_OP_I32_ATOMIC_RMW_AND] = { "i32_atomic_rmw_and", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_AND_U] = { "i32_atomic_rmw8_and_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_AND_U] = { "i32_atomic_rmw16_and_u", STORE, 2 },
    [WASM_OP_I32_ATOMIC_RMW_OR] = { "i32_atomic_rmw_or", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_OR_U] = { "i32_atomic_rmw8_or_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_OR_U] = { "i32_atomic_rmw16_or_u", STORE, 2 },
    [WASM_OP_I32_ATOMIC_RMW_XOR] = { "i32_atomic_rmw_xor", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_XOR_U] = { "i32_atomic_rmw8_xor_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_XOR_U] = { "i32_atomic_rmw16_xor_u", STORE, 2 },
    [WASM_OP_I32_ATOMIC_RMW_XCHG] = { "i32_atomic_rmw_xchg", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_XCHG_U] = { "i32_atomic_rmw8_xchg_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_XCHG_U] = { "i32_atomic_rmw16_xchg_u", STORE, 2 },

    [WASM_OP_I64_STORE] = { "i64_store", STORE, 8, NON_ATOMIC },
    [WASM_OP_I64_STORE8] = { "i64_store8", STORE, 1, NON_ATOMIC },
    [WASM_OP_I64_STORE16] = { "i64_store16", STORE, 2, NON_ATOMIC },
    [WASM_OP_I64_STORE32] = { "i64_store32", STORE, 4, NON_ATOMIC },
    [WASM_OP_I64_ATOMIC_STORE] = { "i64_atomic_store", STORE, 8 },
    [WASM_OP_I64_ATOMIC_STORE8] = { "i64_atomic_store8", STORE, 1 },
    [WASM_OP_I64_ATOMIC_STORE16] = { "i64_atomic_store16", STORE, 2 },
    [WASM_OP_I64_ATOMIC_STORE32] = { "i64_atomic_store32", STORE, 4 },
    [WASM_OP_I64_ATOMIC_RMW_ADD] = { "i64_atomic_rmw_add", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_ADD_U] = { "i64_atomic_rmw8_add_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_ADD_U] = { "i64_atomic_rmw16_add_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_ADD_U] = { "i64_atomic_rmw32_add_u", STORE, 4 },
    [WASM_OP_I64_ATOMIC_RMW_SUB] = { "i64_atomic_rmw_sub", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_SUB_U] = { "i64_atomic_rmw8_sub_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_SUB_U] = { "i64_atomic_rmw16_sub_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_SUB_U] = { "i64_atomic_rmw32_sub_u", STORE, 4 },
    [WASM_OP_I64_ATOMIC_RMW_AND] = { "i64_atomic_rmw_and", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_AND_U] = { "i64_atomic_rmw8_and_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_AND_U] = { "i64_atomic_rmw16_and_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_AND_U] = { "i64_atomic_rmw32_and_u", STORE, 4 },
    [WASM_OP_I64_ATOMIC_RMW_OR] = { "i64_atomic_rmw_or", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_OR_U] = { "i64_atomic_rmw8_or_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_OR_U] = { "i64_atomic_rmw16_or_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_OR_U] = { "i64_atomic_rmw32_or_u", STORE, 4 },
    [WASM_OP_I64_ATOMIC_RMW_XOR] = { "i64_atomic_rmw_xor", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_XOR_U] = { "i64_atomic_rmw8_xor_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_XOR_U] = { "i64_atomic_rmw16_xor_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_XOR_U] = { "i64_atomic_rmw32_xor_u", STORE, 4 },
    [WASM_OP_I64_ATOMIC_RMW_XCHG] = { "i64_atomic_rmw_xchg", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_XCHG_U] = { "i64_atomic_rmw8_xchg_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_XCHG_U] = { "i64_atomic_rmw16_xchg_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_XCHG_U] = { "i64_atomic_rmw32_xchg_u", STORE, 4 },

    [WASM_OP_F32_STORE] = { "f32_store", STORE, 4, NON_ATOMIC },

    [WASM_OP_F64_STORE] = { "f64_store", STORE, 8, NON_ATOMIC },

    [WASM_OP_I32_ATOMIC_RMW_CMPXCHG] = { "i32_atomic_rmw_cmpxchg", STORE, 4 },
    [WASM_OP_I32_ATOMIC_RMW8_CMPXCHG_U] = { "i32_atomic_rmw8_cmpxchg_u", STORE, 1 },
    [WASM_OP_I32_ATOMIC_RMW16_CMPXCHG_U] = { "i32_atomic_rmw16_cmpxchg_u", STORE, 2 },

    [WASM_OP_I64_ATOMIC_RMW_CMPXCHG] = { "i64_atomic_rmw_cmpxchg", STORE, 8 },
    [WASM_OP_I64_ATOMIC_RMW8_CMPXCHG_U] = { "i64_atomic_rmw8_cmpxchg_u", STORE, 1 },
    [WASM_OP_I64_ATOMIC_RMW16_CMPXCHG_U] = { "i64_atomic_rmw16_cmpxchg_u", STORE, 2 },
    [WASM_OP_I64_ATOMIC_RMW32_CMPXCHG_U] = { "i64_atomic_rmw32_cmpxchg_u", STORE, 4 }
};

